export const autoGeneratedPassword = (): string => {
  let password = "";
  for (let i = 0; i < 7; i++) {
    const num = Math.floor(Math.random() * 10);
    password += num;
  }
  return password;
};
